USE [IHR_RAP];
GO


CREATE TABLE [Member].[MnR_Master_Data_Extract]
(   MBR_HICN_NUM                 VARCHAR(12)    NOT NULL    PRIMARY KEY
  , RPT_MO_KEY                   INT                NULL
  , MBR_VDS_ID                   VARCHAR(25)        NULL
  , MBR_INDV_ID                  INT                NULL
  , MBR_INDV_ID_STR              VARCHAR(15)        NULL
  , MBR_CRD_ID                   VARCHAR(30)        NULL
  , MBR_CURR_CMS_CONTR_NUM       VARCHAR(5)         NULL
  , MBR_CURR_CMS_PBP_CD          VARCHAR(3)         NULL
  , MBR_LST_NM                   VARCHAR(100)       NULL
  , MBR_FST_NM                   VARCHAR(100)       NULL
  , MBR_MIDL_INIT                VARCHAR(1)         NULL
  , MBR_DOB                      DATE               NULL
  , MBR_GDR_CD                   VARCHAR(1)         NULL
  , MBR_ADR_LN1_TXT              VARCHAR(100)       NULL
  , MBR_ADR_LN2_TXT              VARCHAR(100)       NULL
  , MBR_ADR_CTY_NM               VARCHAR(50)        NULL
  , MBR_ADR_ST_CD                VARCHAR(2)         NULL
  , MBR_ADR_ZIP_FULL_CD          VARCHAR(10)        NULL
  , MBR_DAY_PH_NUM               VARCHAR(15)        NULL
  , MBR_ANNL_CARE_VST_FLG        BIT                NULL
  , MBR_ANNL_CARE_VST_DT         DATE               NULL
  , MBR_ANNL_CARE_VST_DT_HC      DATE               NULL
  , MBR_DIAB_IND                 BIT                NULL
  , MBR_INCNT_PGM_IND            VARCHAR(25)        NULL
  , MBR_TYP_CD                   VARCHAR(5)         NULL
  , SRC_SYS                      VARCHAR(25)        NULL
  , ASGN_PROV_VDS_ID             VARCHAR(25)        NULL
  , ASGN_PROV_MPIN_NUM           INT                NULL
  , ASGN_PROV_NPI_NUM            BIGINT             NULL
  , ASGN_PROV_TIN_NUM            INT                NULL
  , ASGN_PROV_LST_NM             VARCHAR(100)       NULL
  , ASGN_PROV_FST_NM             VARCHAR(100)       NULL
  , ASGN_PROV_ADR_LN1_TXT        VARCHAR(100)       NULL
  , ASGN_PROV_ADR_LN2_TXT        VARCHAR(100)       NULL
  , ASGN_PROV_ADR_CTY_NM         VARCHAR(50)        NULL
  , ASGN_PROV_ADR_ST_CD          VARCHAR(2)         NULL
  , ASGN_PROV_ADR_ZIP_FULL_CD    VARCHAR(10)        NULL
  , MSR_1_BCS_RSLT               BIT                NULL
  , MSR_2_COL_RSLT               BIT                NULL
  , MSR_3_CMCSCR_RSLT            BIT                NULL
  , MSR_4_CDCLPP_RSLT            BIT                NULL
  , MSR_5_GSO_RSLT               BIT                NULL
  , MSR_12_ABA_RSLT              BIT                NULL
  , MSR_13_COAMR_RSLT            BIT                NULL
  , MSR_14_COAFSA_RSLT           BIT                NULL
  , MSR_15_COAPS_RSLT            BIT                NULL
  , MSR_16_OMW_RSLT              BIT                NULL
  , MSR_16_OMW_DT                DATE               NULL
  , MSR_91_OMWX_RSLT             BIT                NULL
  , MSR_91_OMWX_DT               DATE               NULL
  , MSR_17_CDCEYE_RSLT           BIT                NULL
  , MSR_18_CDCNEP_RSLT           BIT                NULL
  , MSR_19_CDCA1C9_RSLT          BIT                NULL
  , MSR_20_CDC100_RSLT           BIT                NULL
  , MSR_21_CBP_RSLT              TINYINT            NULL
  , MSR_22_ART_RSLT              TINYINT            NULL
  , MSR_49_HRM_PYR_RSLT          BIT                NULL
  , MSR_49_HRM_CYR_STS           VARCHAR(1)         NULL
  , MSR_49_HRM_CYR_RSLT          BIT                NULL
  , MSR_51_MAD_PYR_RSLT          BIT                NULL
  , MSR_51_MAD_CYR_STS           VARCHAR(1)         NULL
  , MSR_51_MAD_CYR_RSLT          TINYINT            NULL
  , MSR_51_MAD_CURR_PDC          DECIMAL(3,2)       NULL
  , MSR_51_MAD_FA_CYR_RSLT       TINYINT            NULL
  , MSR_51_MAD_AD                SMALLINT           NULL
  , MSR_51_MAD_DM45              SMALLINT           NULL
  , MSR_51_MAD_EOY_PDC_PRED      DECIMAL(3,2)       NULL
  , MSR_52_MAH_PYR_RSLT          BIT                NULL
  , MSR_52_MAH_CYR_STS           VARCHAR(1)         NULL
  , MSR_52_MAH_CYR_RSLT          TINYINT            NULL
  , MSR_52_MAH_CURR_PDC          DECIMAL(3,2)       NULL
  , MSR_52_MAH_FA_CYR_RSLT       TINYINT            NULL
  , MSR_52_MAH_AD                SMALLINT           NULL
  , MSR_52_MAH_DM45              SMALLINT           NULL
  , MSR_52_MAH_EOY_PDC_PRED      DECIMAL(3,2)       NULL
  , MSR_53_MAC_PYR_RSLT          BIT                NULL
  , MSR_53_MAC_CYR_STS           VARCHAR(1)         NULL
  , MSR_53_MAC_CYR_RSLT          TINYINT            NULL
  , MSR_53_MAC_CURR_PDC          DECIMAL(3,2)       NULL
  , MSR_53_MAC_FA_CYR_RSLT       TINYINT            NULL
  , MSR_53_MAC_AD                SMALLINT           NULL
  , MSR_53_MAC_DM45              SMALLINT           NULL
  , MSR_53_MAC_EOY_PDC_PRED      DECIMAL(3,2)       NULL
  , MSR_100_SUPD_PYR_RSLT        BIT                NULL
  , MSR_100_SUPD_CYR_STS         VARCHAR(1)         NULL
  , MSR_100_SUPD_CYR_RSLT        BIT                NULL
  , MSR_101_SPC_RSLT             BIT                NULL
  , MSR_58_FMI_RSLT              BIT                NULL
  , MSR_60_AMM_RSLT              BIT                NULL
  , MSR_61_BBT_RSLT              BIT                NULL
  , MSR_62_MPLM_RSLT             BIT                NULL
  , MSR_64_COPD_RSLT             BIT                NULL
  , MSR_71_PCE_SC_RSLT           BIT                NULL
  , MSR_72_PCEBRON_RSLT          BIT                NULL
  , MSR_73_AODRINITOT_RSLT       BIT                NULL
  , MSR_74_EADT_RSLT             BIT                NULL
  , ASSOC_PROV_VDS_ID            VARCHAR(25)        NULL
  , ASSOC_PROV_MPIN_NUM          INT                NULL
  , ASSOC_PROV_NPI_NUM           BIGINT             NULL
  , ASSOC_PROV_TIN               INT                NULL
  , ASSOC_PROV_LST_NM            VARCHAR(100)       NULL
  , ASSOC_PROV_FST_NM            VARCHAR(100)       NULL
  , ASSOC_PROV_ADR_LN1_TXT       VARCHAR(100)       NULL
  , ASSOC_PROV_ADR_LN2_TXT       VARCHAR(100)       NULL
  , ASSOC_PROV_ADR_CTY_NM        VARCHAR(50)        NULL
  , ASSOC_PROV_ADR_ST_CD         VARCHAR(2)         NULL
  , ASSOC_PROV_ADR_ZIP_FULL_CD   VARCHAR(10)        NULL
  , ASSOC_PROV_ASGN_RNDR_IND     VARCHAR(1)         NULL
  , ASSOC_PROV_GRP_TYP_CD        VARCHAR(30)        NULL
  , ASSOC_PROV_GRP_ID            VARCHAR(200)       NULL
  , ASSOC_PROV_GRP_NM            VARCHAR(255)       NULL
  , ASSOC_HLTH_SYS_ID            VARCHAR(255)       NULL
  , ASSOC_HLTH_SYS_NM            VARCHAR(255)       NULL
  , ROW_INSRT_DT                 DATETIME           NULL
  , LST_HICN_BFR_MBI             VARCHAR(15)        NULL
  , SegmentID                    TINYINT            NULL
  , MSR_RSLT_86                  BIT                NULL
  , PARTD_ALRT_LVL_86            VARCHAR(1)         NULL
  , MSR_RSLT_CY_86               BIT                NULL
  , Load_Date_Py                 DATETIME           NULL
  , CountOfFiles                 INT                NULL
  , FileName                     VARCHAR(255)       NULL
  , InsertDate                   DATETIME           NULL
  , LastModifiedDate             DATETIME           NULL
  , DropDate                     DATETIME           NULL
  , MnR_Status                   VARCHAR(20)        NULL
  , MnR_SubStatus                VARCHAR(20)        NULL
  , INDEX IX_MDE_HICN_NUM NONCLUSTERED (MBR_HICN_NUM)
)
;
GO